### ISSUE TITLE
Enhancement Request - Admin Permission

### ISSUE THREAD

**Issue by ValhallaCommunity** [blaxxun-boop/TombstoneLock#2]
Hey Blaxxun,

Can we enhance the mod to have admins ignore the PickupPermission setting and always have access? This will help our leads support players and check tombstone-inventory integrity. 

Thank you for consideration!

Discord tag if questions: WD40PyRO#4575 in OdinPlus

**Comment by blaxxun-boop** [comment]
`tombstone admin` in the console does exactly this.
